package org.example.gymbackend.entity;

public enum Status {

    START,SHARE_CONTACT,SET_PASSWORD,SET_SETTING,SET_IMAGE,SET_NAME, TARIF_ADD, ADD_SUBSCRIPTION_NAME, ADD_SUBSCRIPTION_REQUEST_PRICE, ADD_SUBSCRIPTION_REQUEST_TITLE, ADD_SUBSCRIPTION_REQUEST_DAY_COUNT, SET_RATE, SET_ODD_AND_EVEN, SET_SEARCH
//    START,SHARE_CONTACT,SET_PASSWORD,SET_SETTING,SET_IMAGE,SET_NAME, TARIF_ADD, ADD_SUBSCRIPTION_NAME, ADD_SUBSCRIPTION_REQUEST_PRICE, ADD_SUBSCRIPTION_REQUEST_TITLE, ADD_SUBSCRIPTION_REQUEST_DAY_COUNT, SET_ODD_AND_EVEN, SET_SAVE_TARIF, SET_RATE
}